print("Welcome to the band name generator")
city = input("What's the name of the city you grew up in?\n")
print(city)
pet = input("What's your pet's name?\n")
print(pet)
print("Your band name could be: " + city + " " + pet)